import pandas as pd
from pathlib import Path

WORKFLOW = Path("workflow").resolve()
CONFIG = Path("config").resolve()
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESULTS = Path("results").resolve()
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
BENCH = RESULTS / "benchmark"
LOGS = Path("logs/rules").resolve()


configfile: CONFIG / "config.yaml"


samplesheet = pd.read_csv(config["samplesheet"], sep="\t", index_col="Run Accession")
# for testing we use a smaller set of samples
# samplesheet = samplesheet.sample(n=2000, random_state=1)

# print(len(samplesheet.query("`Instrument Platform` == 'PACBIO_SMRT'")))
# print(len(samplesheet.query("`Instrument Platform` == 'OXFORD_NANOPORE'")))

methods = ["lrge-ava", "lrge-2set", "mash", "genomescope"]
combine_estimate_paths = []
combine_benchmark_paths = []
combine_stats_paths = []

for run in samplesheet.index:
    # run accession is (E|D|S)RR[0-9]{6,}
    dir1 = run[:3]  # ERR, SRR, DRR
    dir2 = run[3:6]  # first three digits
    dir3 = run[6:9]  # second three digits as accession will have a minimum of 6 digits

    for method in methods:
        est = RESULTS / f"estimates/{method}/{dir1}/{dir2}/{dir3}/{run}/{run}.size"
        bench = BENCH / f"estimate/{method}/{dir1}/{dir2}/{dir3}/{run}.bench.tsv"
        stats = RESULTS / f"stats/{dir1}/{dir2}/{dir3}/{run}.stats.tsv"
        combine_estimate_paths.append(est)
        combine_benchmark_paths.append(bench)
        combine_stats_paths.append(stats)

targets = set()
targets.add(RESULTS / "estimates/estimates.tsv")


rule all:
    input:
        targets,


include: RULES / "download.smk"
include: RULES / "estimate.smk"
